@baseUrl = http://localhost:8080/api/v1
@contentType = application/json

###
# 1. 로그인 (응답의 token 값을 아래 token 변수에 자동으로 복사)
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "test@example.com",
  "password": "Test1234!"
}

> {% client.global.set("token", response.body.data.accessToken); %}

###
# 2. 주문 미리보기
POST {{baseUrl}}/orders/preview
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "cartItemIds": [1]
}

###
# 3. 주문, 결제 생성
POST {{baseUrl}}/orders
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "cartItemIds": [1],
    "usedPoint": 0
}

###
# 4. 결제 확정
POST {{baseUrl}}/payments/confirm
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "orderId": 1,
    "portonePaymentId": "PAY-ORD-20260605-EE4DB79F-345C040D"
}

###
# 5. 결제 취소
POST {{baseUrl}}/orders/1/cancel
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "cancelReason": "단순 변심"
}