spring.config.import= aws-parameterstore:/3trim-payment/prod/

# MySQL (env vars can override defaults)
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA defaults for local development
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SQL_INIT:never}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/v1

jwt.secret=${jwt-secret}
jwt.expire-time=${jwt-expire-time}

portone.store-id=${store-id}
portone.api-secret=${portone-api-key}